### ISSUE TITLE
Document execution steps & required run arguments

### ISSUE THREAD

**Issue by s-gbz** [adessoAG/blogpost-checker#11]
Execution via docker: `docker run --env REPOSITORY_REMOTE_URL='${{ secrets.REPOSITORY_REMOTE_URL }}' --env REPOSITORY_BRANCH_NAME='${{ github.head_ref }}' jekyll2cms/blogpost-checker:1.0.0`

Required arguments:
- REPOSITORY_REMOTE_URL  (repository to be cloned)
- REPOSITORY_BRANCH_NAME (branch to be scanned)

**Comment by jo2** [comment]
Currently there is a PR open fox expading the readme, it is marked as WIP right now, but you can add it there. Can you add the necessary parameters and the docker command, and remove the TODO? Then the pr should be complete and not WIP anymore.

**Comment by s-gbz** [comment]
Closed by #24
